openai_api_key: ${openai-api-key}
connections:
  - name: neon_test
    databaseName: ${db-dbname-neon-test4444}
    schemaName: ${db-schema-neon-test4444}
    dbType: postgres
    url: >-
      jdbc:postgresql://${db-host-neon-test4444}:${db-port-neon-test4444}/${db-dbname-neon-test4444}?currentSchema=${db-schema-neon-test4444}&sslmode=require
    userName: ${db-user-neon-test4444}
    password: ${db-password-neon-test4444}
